In [4]:
import numpy as np

x = np.array([1,2,3,4,5])


In [8]:
print(x)
print(type(x))
x.dtype

[1 2 3 4 5]
<class 'numpy.ndarray'>


dtype('int32')

In [9]:
x.shape

(5,)

In [12]:
y = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(y)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [13]:
y.shape

(3, 5)

In [14]:
y.size

15

In [15]:
z = np.array([1,2.5])
print(z.dtype)

float64


In [2]:
x = np.array([2.5,1],5)
print(x.dtype)

NameError: name 'np' is not defined

In [3]:
np.save('save_array',x)


NameError: name 'np' is not defined

In [18]:
z = np.load('save_array.npy')
print(z)

[2 1]
